//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROG5_LeagueOfNinjas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.LoadoutItems = new HashSet<LoadoutItem>();
            this.PurchasedItems = new HashSet<PurchasedItem>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public int Value { get; set; }
        public Nullable<int> Strength { get; set; }
        public Nullable<int> Intelligence { get; set; }
        public Nullable<int> Agility { get; set; }
        public string Name { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoadoutItem> LoadoutItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchasedItem> PurchasedItems { get; set; }
    }
}
