//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROG5_LeagueOfNinjas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadoutItem
    {
        public int Id { get; set; }
        public int Loadout { get; set; }
        public int Equipment { get; set; }
    
        public virtual Equipment Equipment1 { get; set; }
        public virtual Loadout Loadout1 { get; set; }
    }
}
